# Generated by Django 4.2.5 on 2023-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_liburuak_autorea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liburuak',
            name='noizsortua',
            field=models.DateField(auto_now_add=True),
        ),
    ]
