# Generated by Django 4.2.5 on 2023-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_liburuak_noizsortua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreak',
            name='jaiotze_data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='liburuak',
            name='noizsortua',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
